/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DRBDSpecApplyConfiguration represents a declarative configuration of the DRBDSpec type for use
// with apply.
//
// DRBDSpec carries the cluster-unique DRBD identifiers allocated by the
// controller. The Minor is per-node and managed locally by each agent.
// Unset for replicas:1 volumes (no replication layer).
type DRBDSpecApplyConfiguration struct {
	// Port is the TCP port for this resource's replication links,
	// allocated cluster-wide by the controller at creation.
	Port *int32 `json:"port,omitempty"`
	// SharedSecret authenticates peers (cram-hmac-alg challenge-response):
	// without it, anything that can reach the replication port can join the
	// resource. Generated by the controller at creation; both agents render
	// the same value. DRBD caps secrets at 64 characters.
	SharedSecret *string `json:"sharedSecret,omitempty"`
	// BitmapGranularityBytes is the DRBD bitmap block size handed to
	// create-md (--bitmap-block-size): each dirty bit tracks this many
	// bytes, so coarser bits cut bitmap RAM proportionally at the cost of
	// resyncing more per dirty bit. Applied only when a replica's metadata
	// is first created — replicas created earlier keep their granularity
	// (DRBD exchanges bitmaps across differing block sizes). 0 means the
	// DRBD default (4096). Needs kmod ≥ 9.3.1 (the agent's startup floor).
	BitmapGranularityBytes *int64 `json:"bitmapGranularityBytes,omitempty"`
}

// DRBDSpecApplyConfiguration constructs a declarative configuration of the DRBDSpec type for use with
// apply.
func DRBDSpec() *DRBDSpecApplyConfiguration {
	return &DRBDSpecApplyConfiguration{}
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *DRBDSpecApplyConfiguration) WithPort(value int32) *DRBDSpecApplyConfiguration {
	b.Port = &value
	return b
}

// WithSharedSecret sets the SharedSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SharedSecret field is set to the value of the last call.
func (b *DRBDSpecApplyConfiguration) WithSharedSecret(value string) *DRBDSpecApplyConfiguration {
	b.SharedSecret = &value
	return b
}

// WithBitmapGranularityBytes sets the BitmapGranularityBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BitmapGranularityBytes field is set to the value of the last call.
func (b *DRBDSpecApplyConfiguration) WithBitmapGranularityBytes(value int64) *DRBDSpecApplyConfiguration {
	b.BitmapGranularityBytes = &value
	return b
}
