/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ExportStatusApplyConfiguration represents a declarative configuration of the ExportStatus type for use
// with apply.
//
// ExportStatus is the observed state of an RWX volume's NFS gateway,
// written by the export reconciler.
type ExportStatusApplyConfiguration struct {
	// Address is the share Service's ClusterIP. Consumers mount
	// <address>:/<volume> over NFS. Empty until the reconciler has
	// created the Service and read back its allocated ClusterIP.
	Address *string `json:"address,omitempty"`
}

// ExportStatusApplyConfiguration constructs a declarative configuration of the ExportStatus type for use with
// apply.
func ExportStatus() *ExportStatusApplyConfiguration {
	return &ExportStatusApplyConfiguration{}
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *ExportStatusApplyConfiguration) WithAddress(value string) *ExportStatusApplyConfiguration {
	b.Address = &value
	return b
}
