/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ExportSpecApplyConfiguration represents a declarative configuration of the ExportSpec type for use
// with apply.
//
// ExportSpec turns the volume into a shared filesystem (RWX): a gateway
// pod on one replica node stages the device and serves it over NFS;
// consumers on any node mount the export. The gateway is the volume's
// only writer, so DRBD single-primary fencing is unchanged (no
// allow-two-primaries). Set at creation from a MULTI_NODE access mode
// and immutable thereafter.
type ExportSpecApplyConfiguration struct {
	// FSType is the filesystem the gateway formats and mounts on the
	// device. Persisted here because mkfs happens in the gateway, which
	// never sees a CSI VolumeCapability; consumers only ever see NFS.
	FSType *string `json:"fsType,omitempty"`
}

// ExportSpecApplyConfiguration constructs a declarative configuration of the ExportSpec type for use with
// apply.
func ExportSpec() *ExportSpecApplyConfiguration {
	return &ExportSpecApplyConfiguration{}
}

// WithFSType sets the FSType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FSType field is set to the value of the last call.
func (b *ExportSpecApplyConfiguration) WithFSType(value string) *ExportSpecApplyConfiguration {
	b.FSType = &value
	return b
}
