/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// LoopfilePoolApplyConfiguration represents a declarative configuration of the LoopfilePool type for use
// with apply.
//
// LoopfilePool configures a loopfile pool: loop-backed sparse files on the
// node's existing filesystem — no dedicated disk or pool.
type LoopfilePoolApplyConfiguration struct {
	// BaseDir is the directory holding the sparse files, e.g.
	// "/var/lib/miroir". Must be reflink-capable (XFS reflink=1 or btrfs)
	// for CoW snapshots; the agent refuses the pool otherwise.
	BaseDir *string `json:"baseDir,omitempty"`
}

// LoopfilePoolApplyConfiguration constructs a declarative configuration of the LoopfilePool type for use with
// apply.
func LoopfilePool() *LoopfilePoolApplyConfiguration {
	return &LoopfilePoolApplyConfiguration{}
}

// WithBaseDir sets the BaseDir field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseDir field is set to the value of the last call.
func (b *LoopfilePoolApplyConfiguration) WithBaseDir(value string) *LoopfilePoolApplyConfiguration {
	b.BaseDir = &value
	return b
}
