/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// LVMThinPoolApplyConfiguration represents a declarative configuration of the LVMThinPool type for use
// with apply.
//
// LVMThinPool configures an lvmthin pool: a dm-thin pool on the LVM VG
// vg-miroir (default pool) or vg-miroir-<pool>.
type LVMThinPoolApplyConfiguration struct {
	// Device is the block device backing the pool's VG. Optional when the
	// VG already exists (a pre-provisioned or shared VG); required for the
	// agent to create it on first start.
	Device *string `json:"device,omitempty"`
	// PoolSize bounds the thin pool (an lvm size spec, e.g. "400g");
	// empty claims all free VG space.
	PoolSize *string `json:"poolSize,omitempty"`
}

// LVMThinPoolApplyConfiguration constructs a declarative configuration of the LVMThinPool type for use with
// apply.
func LVMThinPool() *LVMThinPoolApplyConfiguration {
	return &LVMThinPoolApplyConfiguration{}
}

// WithDevice sets the Device field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Device field is set to the value of the last call.
func (b *LVMThinPoolApplyConfiguration) WithDevice(value string) *LVMThinPoolApplyConfiguration {
	b.Device = &value
	return b
}

// WithPoolSize sets the PoolSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PoolSize field is set to the value of the last call.
func (b *LVMThinPoolApplyConfiguration) WithPoolSize(value string) *LVMThinPoolApplyConfiguration {
	b.PoolSize = &value
	return b
}
