/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MiroirNodeGroupSpecApplyConfiguration represents a declarative configuration of the MiroirNodeGroupSpec type for use
// with apply.
//
// MiroirNodeGroupSpec selects a set of nodes and the MiroirNode spec they
// share.
type MiroirNodeGroupSpecApplyConfiguration struct {
	// NodeSelector picks the member nodes by label. An empty selector
	// matches every node in the cluster (the Kubernetes convention).
	NodeSelector *v1.LabelSelectorApplyConfiguration `json:"nodeSelector,omitempty"`
	// Template is the MiroirNode spec applied to every member, with two
	// per-node facts resolved from the Node object: an empty zone
	// inherits the node's topology.kubernetes.io/zone label, and the
	// replication address comes from the node's
	// miroir.home-operations.com/address annotation.
	Template *MiroirNodeSpecApplyConfiguration `json:"template,omitempty"`
}

// MiroirNodeGroupSpecApplyConfiguration constructs a declarative configuration of the MiroirNodeGroupSpec type for use with
// apply.
func MiroirNodeGroupSpec() *MiroirNodeGroupSpecApplyConfiguration {
	return &MiroirNodeGroupSpecApplyConfiguration{}
}

// WithNodeSelector sets the NodeSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeSelector field is set to the value of the last call.
func (b *MiroirNodeGroupSpecApplyConfiguration) WithNodeSelector(value *v1.LabelSelectorApplyConfiguration) *MiroirNodeGroupSpecApplyConfiguration {
	b.NodeSelector = value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *MiroirNodeGroupSpecApplyConfiguration) WithTemplate(value *MiroirNodeSpecApplyConfiguration) *MiroirNodeGroupSpecApplyConfiguration {
	b.Template = value
	return b
}
