/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/home-operations/miroir/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MiroirVolumeStatusApplyConfiguration represents a declarative configuration of the MiroirVolumeStatus type for use
// with apply.
//
// MiroirVolumeStatus is the observed state aggregated from node agents.
type MiroirVolumeStatusApplyConfiguration struct {
	// Phase summarizes the volume state for the controller and humans.
	Phase *apiv1alpha1.VolumePhase `json:"phase,omitempty"`
	// ReadyReplicas summarizes diskful replica readiness as "ready/total"
	// (diskless tie-breakers and client legs excluded, like Phase). A
	// preformatted string because CRD printcolumns cannot combine two
	// integer fields into one cell.
	ReadyReplicas *string `json:"readyReplicas,omitempty"`
	// PerNode maps node name to that agent's observed state.
	PerNode map[string]ReplicaStatusApplyConfiguration `json:"perNode,omitempty"`
	// Export is the observed state of the NFS gateway, set only on RWX
	// volumes (spec.export). Written by the export reconciler.
	Export *ExportStatusApplyConfiguration `json:"export,omitempty"`
	// Formatted is set once the volume has ever carried a filesystem —
	// first mkfs at stage time, or inherited from the snapshot source on
	// restore. A blank device on a formatted volume is data loss: the
	// node refuses to mkfs again rather than silently wipe it.
	Formatted *bool `json:"formatted,omitempty"`
	// Activated is set the first time any node successfully stages the
	// volume for a consumer (filesystem or raw block). It latches "this
	// volume may hold data": split-brain auto-recovery, which discards one
	// leg's generation, runs only while this is false — on an activated
	// volume divergence is never auto-resolved. Broader than Formatted,
	// which a raw-block volume never sets.
	Activated *bool `json:"activated,omitempty"`
	// Conditions follow the standard Kubernetes condition conventions.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MiroirVolumeStatusApplyConfiguration constructs a declarative configuration of the MiroirVolumeStatus type for use with
// apply.
func MiroirVolumeStatus() *MiroirVolumeStatusApplyConfiguration {
	return &MiroirVolumeStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *MiroirVolumeStatusApplyConfiguration) WithPhase(value apiv1alpha1.VolumePhase) *MiroirVolumeStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *MiroirVolumeStatusApplyConfiguration) WithReadyReplicas(value string) *MiroirVolumeStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithPerNode puts the entries into the PerNode field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PerNode field,
// overwriting an existing map entries in PerNode field with the same key.
func (b *MiroirVolumeStatusApplyConfiguration) WithPerNode(entries map[string]ReplicaStatusApplyConfiguration) *MiroirVolumeStatusApplyConfiguration {
	if b.PerNode == nil && len(entries) > 0 {
		b.PerNode = make(map[string]ReplicaStatusApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.PerNode[k] = v
	}
	return b
}

// WithExport sets the Export field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Export field is set to the value of the last call.
func (b *MiroirVolumeStatusApplyConfiguration) WithExport(value *ExportStatusApplyConfiguration) *MiroirVolumeStatusApplyConfiguration {
	b.Export = value
	return b
}

// WithFormatted sets the Formatted field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Formatted field is set to the value of the last call.
func (b *MiroirVolumeStatusApplyConfiguration) WithFormatted(value bool) *MiroirVolumeStatusApplyConfiguration {
	b.Formatted = &value
	return b
}

// WithActivated sets the Activated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Activated field is set to the value of the last call.
func (b *MiroirVolumeStatusApplyConfiguration) WithActivated(value bool) *MiroirVolumeStatusApplyConfiguration {
	b.Activated = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MiroirVolumeStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MiroirVolumeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
