/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MiroirNodeGroupStatusApplyConfiguration represents a declarative configuration of the MiroirNodeGroupStatus type for use
// with apply.
//
// MiroirNodeGroupStatus reports the group's materialized membership.
type MiroirNodeGroupStatusApplyConfiguration struct {
	// Nodes lists the member nodes whose MiroirNode this group currently
	// manages, sorted by name.
	Nodes []string `json:"nodes,omitempty"`
	// ObservedGeneration is the spec generation this status reflects.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions follow the standard Kubernetes condition conventions.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MiroirNodeGroupStatusApplyConfiguration constructs a declarative configuration of the MiroirNodeGroupStatus type for use with
// apply.
func MiroirNodeGroupStatus() *MiroirNodeGroupStatusApplyConfiguration {
	return &MiroirNodeGroupStatusApplyConfiguration{}
}

// WithNodes adds the given value to the Nodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Nodes field.
func (b *MiroirNodeGroupStatusApplyConfiguration) WithNodes(values ...string) *MiroirNodeGroupStatusApplyConfiguration {
	for i := range values {
		b.Nodes = append(b.Nodes, values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *MiroirNodeGroupStatusApplyConfiguration) WithObservedGeneration(value int64) *MiroirNodeGroupStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MiroirNodeGroupStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MiroirNodeGroupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
