/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/home-operations/miroir/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MiroirSnapshotStatusApplyConfiguration represents a declarative configuration of the MiroirSnapshotStatus type for use
// with apply.
//
// MiroirSnapshotStatus is the observed state aggregated from node agents.
// The snapshot exists as a backend CoW snapshot on every replica of the
// source volume (DESIGN.md §4.5.4).
type MiroirSnapshotStatusApplyConfiguration struct {
	// ReadyToUse is true once every replica holds the snapshot.
	ReadyToUse *bool `json:"readyToUse,omitempty"`
	// PerNode maps node name to that agent's snapshot progress.
	PerNode map[string]apiv1alpha1.SnapshotNodeState `json:"perNode,omitempty"`
	// SizeBytes is the virtual size of the snapshotted volume, used by
	// the CSI layer to size restored volumes.
	SizeBytes *int64 `json:"sizeBytes,omitempty"`
	// SourceFormatted records the source volume's Formatted flag when
	// the snapshot is cut. Restored volumes inherit it so their first
	// stage never reformats a clone that should carry a filesystem.
	SourceFormatted *bool `json:"sourceFormatted,omitempty"`
	// IOSuspended is the replicated-snapshot write barrier: set by the
	// coordinator after suspend-io, cleared on resume. Peers snapshot
	// only while it holds.
	IOSuspended *bool `json:"ioSuspended,omitempty"`
	// SuspendedAt bounds the barrier: the coordinator resumes IO at the
	// deadline even if a peer never snapshots.
	SuspendedAt *v1.Time `json:"suspendedAt,omitempty"`
	// Conditions follow the standard Kubernetes condition conventions.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MiroirSnapshotStatusApplyConfiguration constructs a declarative configuration of the MiroirSnapshotStatus type for use with
// apply.
func MiroirSnapshotStatus() *MiroirSnapshotStatusApplyConfiguration {
	return &MiroirSnapshotStatusApplyConfiguration{}
}

// WithReadyToUse sets the ReadyToUse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyToUse field is set to the value of the last call.
func (b *MiroirSnapshotStatusApplyConfiguration) WithReadyToUse(value bool) *MiroirSnapshotStatusApplyConfiguration {
	b.ReadyToUse = &value
	return b
}

// WithPerNode puts the entries into the PerNode field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PerNode field,
// overwriting an existing map entries in PerNode field with the same key.
func (b *MiroirSnapshotStatusApplyConfiguration) WithPerNode(entries map[string]apiv1alpha1.SnapshotNodeState) *MiroirSnapshotStatusApplyConfiguration {
	if b.PerNode == nil && len(entries) > 0 {
		b.PerNode = make(map[string]apiv1alpha1.SnapshotNodeState, len(entries))
	}
	for k, v := range entries {
		b.PerNode[k] = v
	}
	return b
}

// WithSizeBytes sets the SizeBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SizeBytes field is set to the value of the last call.
func (b *MiroirSnapshotStatusApplyConfiguration) WithSizeBytes(value int64) *MiroirSnapshotStatusApplyConfiguration {
	b.SizeBytes = &value
	return b
}

// WithSourceFormatted sets the SourceFormatted field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceFormatted field is set to the value of the last call.
func (b *MiroirSnapshotStatusApplyConfiguration) WithSourceFormatted(value bool) *MiroirSnapshotStatusApplyConfiguration {
	b.SourceFormatted = &value
	return b
}

// WithIOSuspended sets the IOSuspended field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IOSuspended field is set to the value of the last call.
func (b *MiroirSnapshotStatusApplyConfiguration) WithIOSuspended(value bool) *MiroirSnapshotStatusApplyConfiguration {
	b.IOSuspended = &value
	return b
}

// WithSuspendedAt sets the SuspendedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuspendedAt field is set to the value of the last call.
func (b *MiroirSnapshotStatusApplyConfiguration) WithSuspendedAt(value v1.Time) *MiroirSnapshotStatusApplyConfiguration {
	b.SuspendedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MiroirSnapshotStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *MiroirSnapshotStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
