/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MiroirSnapshotGroupSpecApplyConfiguration represents a declarative configuration of the MiroirSnapshotGroupSpec type for use
// with apply.
//
// MiroirSnapshotGroupSpec is the desired state, created by the controller
// on CSI CreateVolumeGroupSnapshot.
type MiroirSnapshotGroupSpecApplyConfiguration struct {
	// SnapshotNames lists the member MiroirSnapshots (one per source
	// volume, each carrying this group's name in spec.group). Immutable:
	// the group barrier is cut atomically over exactly this member set,
	// so growing or shrinking it after the fact would misrepresent what
	// the cut covered.
	SnapshotNames []string `json:"snapshotNames,omitempty"`
}

// MiroirSnapshotGroupSpecApplyConfiguration constructs a declarative configuration of the MiroirSnapshotGroupSpec type for use with
// apply.
func MiroirSnapshotGroupSpec() *MiroirSnapshotGroupSpecApplyConfiguration {
	return &MiroirSnapshotGroupSpecApplyConfiguration{}
}

// WithSnapshotNames adds the given value to the SnapshotNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SnapshotNames field.
func (b *MiroirSnapshotGroupSpecApplyConfiguration) WithSnapshotNames(values ...string) *MiroirSnapshotGroupSpecApplyConfiguration {
	for i := range values {
		b.SnapshotNames = append(b.SnapshotNames, values[i])
	}
	return b
}
