/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MiroirNodePoolStatusApplyConfiguration represents a declarative configuration of the MiroirNodePoolStatus type for use
// with apply.
//
// MiroirNodePoolStatus is one pool's capacity figures.
// On a shared pool (e.g. ZFS shared with OpenEBS) the figures are
// pool-level, so a co-tenant's growth correctly shrinks miroir's headroom.
type MiroirNodePoolStatusApplyConfiguration struct {
	// Name is the pool name from the node map.
	Name *string `json:"name,omitempty"`
	// CapacityBytes is the total size of this node-local pool.
	CapacityBytes *int64 `json:"capacityBytes,omitempty"`
	// AllocatedBytes is the pool capacity currently used (all tenants).
	AllocatedBytes *int64 `json:"allocatedBytes,omitempty"`
	// MetaUsedPercent is the dm-thin metadata usage (lvmthin only; 0
	// otherwise), rounded — exhausting metadata wedges the pool
	// independently of data space.
	MetaUsedPercent *int32 `json:"metaUsedPercent,omitempty"`
	// Message carries the last stats-sampling error for this pool, if
	// any — a pool whose backend cannot be read stays visible instead of
	// silently dropping out of the list.
	Message *string `json:"message,omitempty"`
}

// MiroirNodePoolStatusApplyConfiguration constructs a declarative configuration of the MiroirNodePoolStatus type for use with
// apply.
func MiroirNodePoolStatus() *MiroirNodePoolStatusApplyConfiguration {
	return &MiroirNodePoolStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MiroirNodePoolStatusApplyConfiguration) WithName(value string) *MiroirNodePoolStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithCapacityBytes sets the CapacityBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CapacityBytes field is set to the value of the last call.
func (b *MiroirNodePoolStatusApplyConfiguration) WithCapacityBytes(value int64) *MiroirNodePoolStatusApplyConfiguration {
	b.CapacityBytes = &value
	return b
}

// WithAllocatedBytes sets the AllocatedBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllocatedBytes field is set to the value of the last call.
func (b *MiroirNodePoolStatusApplyConfiguration) WithAllocatedBytes(value int64) *MiroirNodePoolStatusApplyConfiguration {
	b.AllocatedBytes = &value
	return b
}

// WithMetaUsedPercent sets the MetaUsedPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetaUsedPercent field is set to the value of the last call.
func (b *MiroirNodePoolStatusApplyConfiguration) WithMetaUsedPercent(value int32) *MiroirNodePoolStatusApplyConfiguration {
	b.MetaUsedPercent = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *MiroirNodePoolStatusApplyConfiguration) WithMessage(value string) *MiroirNodePoolStatusApplyConfiguration {
	b.Message = &value
	return b
}
