/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MiroirNodeStatusApplyConfiguration represents a declarative configuration of the MiroirNodeStatus type for use
// with apply.
//
// MiroirNodeStatus is the pool capacity this node's agent publishes for
// capacity-aware placement and overcommit guardrails (DESIGN.md §4.6).
// On a shared pool (e.g. ZFS shared with OpenEBS) the figures are
// pool-level, so a co-tenant's growth correctly shrinks miroir's headroom.
type MiroirNodeStatusApplyConfiguration struct {
	// CapacityBytes is the total size of the node-local pool.
	CapacityBytes *int64 `json:"capacityBytes,omitempty"`
	// AllocatedBytes is the pool capacity currently used (all tenants).
	AllocatedBytes *int64 `json:"allocatedBytes,omitempty"`
	// MetaUsedPercent is the dm-thin metadata usage (lvmthin only; 0
	// otherwise), rounded — exhausting metadata wedges the pool
	// independently of data space.
	MetaUsedPercent *int32 `json:"metaUsedPercent,omitempty"`
	// ObservedAt is when these figures were last sampled; the controller
	// ignores stats older than a few poll intervals as unknown.
	ObservedAt *v1.Time `json:"observedAt,omitempty"`
	// Conditions follow the standard Kubernetes condition conventions;
	// PoolUsageHigh fires at the 80% data/metadata warn line.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MiroirNodeStatusApplyConfiguration constructs a declarative configuration of the MiroirNodeStatus type for use with
// apply.
func MiroirNodeStatus() *MiroirNodeStatusApplyConfiguration {
	return &MiroirNodeStatusApplyConfiguration{}
}

// WithCapacityBytes sets the CapacityBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CapacityBytes field is set to the value of the last call.
func (b *MiroirNodeStatusApplyConfiguration) WithCapacityBytes(value int64) *MiroirNodeStatusApplyConfiguration {
	b.CapacityBytes = &value
	return b
}

// WithAllocatedBytes sets the AllocatedBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllocatedBytes field is set to the value of the last call.
func (b *MiroirNodeStatusApplyConfiguration) WithAllocatedBytes(value int64) *MiroirNodeStatusApplyConfiguration {
	b.AllocatedBytes = &value
	return b
}

// WithMetaUsedPercent sets the MetaUsedPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetaUsedPercent field is set to the value of the last call.
func (b *MiroirNodeStatusApplyConfiguration) WithMetaUsedPercent(value int32) *MiroirNodeStatusApplyConfiguration {
	b.MetaUsedPercent = &value
	return b
}

// WithObservedAt sets the ObservedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedAt field is set to the value of the last call.
func (b *MiroirNodeStatusApplyConfiguration) WithObservedAt(value v1.Time) *MiroirNodeStatusApplyConfiguration {
	b.ObservedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MiroirNodeStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *MiroirNodeStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
