/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/home-operations/miroir/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MiroirSnapshotGroupStatusApplyConfiguration represents a declarative configuration of the MiroirSnapshotGroupStatus type for use
// with apply.
//
// MiroirSnapshotGroupStatus is the shared state of the group's write
// barrier round. One MiroirSnapshotGroup is one round spanning every
// diskful leg of every member volume — the multi-volume generalization
// of the MiroirSnapshot per-node round, kept on a single object so that
// sealing and voiding the round serialize on one resourceVersion.
type MiroirSnapshotGroupStatusApplyConfiguration struct {
	// ReadyToUse is true once every diskful leg of every member volume
	// holds its snapshot, all cut inside one shared write barrier.
	ReadyToUse *bool `json:"readyToUse,omitempty"`
	// PerLeg maps "<volume>/<node>" to that leg's progress through the
	// group barrier round.
	PerLeg map[string]apiv1alpha1.SnapshotNodeState `json:"perLeg,omitempty"`
	// IOSuspended is the group-wide write barrier: set by the round
	// driver after suspending its local member legs, cleared on resume.
	// Legs are cut only while it holds and every slot reports Suspended.
	IOSuspended *bool `json:"ioSuspended,omitempty"`
	// SuspendedAt bounds the barrier: the driver voids the round at the
	// deadline even if a leg never cuts, so a stuck member cannot freeze
	// every volume in the group forever.
	SuspendedAt *v1.Time `json:"suspendedAt,omitempty"`
	// Conditions follow the standard Kubernetes condition conventions.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MiroirSnapshotGroupStatusApplyConfiguration constructs a declarative configuration of the MiroirSnapshotGroupStatus type for use with
// apply.
func MiroirSnapshotGroupStatus() *MiroirSnapshotGroupStatusApplyConfiguration {
	return &MiroirSnapshotGroupStatusApplyConfiguration{}
}

// WithReadyToUse sets the ReadyToUse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyToUse field is set to the value of the last call.
func (b *MiroirSnapshotGroupStatusApplyConfiguration) WithReadyToUse(value bool) *MiroirSnapshotGroupStatusApplyConfiguration {
	b.ReadyToUse = &value
	return b
}

// WithPerLeg puts the entries into the PerLeg field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PerLeg field,
// overwriting an existing map entries in PerLeg field with the same key.
func (b *MiroirSnapshotGroupStatusApplyConfiguration) WithPerLeg(entries map[string]apiv1alpha1.SnapshotNodeState) *MiroirSnapshotGroupStatusApplyConfiguration {
	if b.PerLeg == nil && len(entries) > 0 {
		b.PerLeg = make(map[string]apiv1alpha1.SnapshotNodeState, len(entries))
	}
	for k, v := range entries {
		b.PerLeg[k] = v
	}
	return b
}

// WithIOSuspended sets the IOSuspended field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IOSuspended field is set to the value of the last call.
func (b *MiroirSnapshotGroupStatusApplyConfiguration) WithIOSuspended(value bool) *MiroirSnapshotGroupStatusApplyConfiguration {
	b.IOSuspended = &value
	return b
}

// WithSuspendedAt sets the SuspendedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuspendedAt field is set to the value of the last call.
func (b *MiroirSnapshotGroupStatusApplyConfiguration) WithSuspendedAt(value v1.Time) *MiroirSnapshotGroupStatusApplyConfiguration {
	b.SuspendedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MiroirSnapshotGroupStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *MiroirSnapshotGroupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
