/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/home-operations/miroir/api/v1alpha1"
)

// MiroirNodePoolApplyConfiguration represents a declarative configuration of the MiroirNodePool type for use
// with apply.
//
// MiroirNodePool is the per-pool slice of a node's spec: which backend
// implementation the named pool runs, mirrored from the node map so
// `kubectl get miroirnodes` reads without the ConfigMap.
type MiroirNodePoolApplyConfiguration struct {
	// Name is the pool name from the node map ("default" for the
	// pre-multi-pool single pool).
	Name *string `json:"name,omitempty"`
	// Backend is the storage implementation backing this pool.
	Backend *apiv1alpha1.BackendType `json:"backend,omitempty"`
}

// MiroirNodePoolApplyConfiguration constructs a declarative configuration of the MiroirNodePool type for use with
// apply.
func MiroirNodePool() *MiroirNodePoolApplyConfiguration {
	return &MiroirNodePoolApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MiroirNodePoolApplyConfiguration) WithName(value string) *MiroirNodePoolApplyConfiguration {
	b.Name = &value
	return b
}

// WithBackend sets the Backend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backend field is set to the value of the last call.
func (b *MiroirNodePoolApplyConfiguration) WithBackend(value apiv1alpha1.BackendType) *MiroirNodePoolApplyConfiguration {
	b.Backend = &value
	return b
}
