/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MiroirNodeSpecApplyConfiguration represents a declarative configuration of the MiroirNodeSpec type for use
// with apply.
//
// MiroirNodeSpec records which pools a storage node runs.
type MiroirNodeSpecApplyConfiguration struct {
	// Pools lists this node's storage pools, one entry per pool.
	Pools []MiroirNodePoolApplyConfiguration `json:"pools,omitempty"`
}

// MiroirNodeSpecApplyConfiguration constructs a declarative configuration of the MiroirNodeSpec type for use with
// apply.
func MiroirNodeSpec() *MiroirNodeSpecApplyConfiguration {
	return &MiroirNodeSpecApplyConfiguration{}
}

// WithPools adds the given value to the Pools field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Pools field.
func (b *MiroirNodeSpecApplyConfiguration) WithPools(values ...*MiroirNodePoolApplyConfiguration) *MiroirNodeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPools")
		}
		b.Pools = append(b.Pools, *values[i])
	}
	return b
}
