/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/home-operations/miroir/api/v1alpha1"
	internal "github.com/home-operations/miroir/api/v1alpha1/applyconfiguration/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MiroirNodeGroupApplyConfiguration represents a declarative configuration of the MiroirNodeGroup type for use
// with apply.
//
// MiroirNodeGroup materializes one MiroirNode per label-matched node, so a
// fleet sharing a storage layout (a device-path convention, a common ZFS
// dataset) is one object and joining it is labeling the node. Direct
// MiroirNodes always win over groups, and membership changes never delete
// a MiroirNode — members that stop matching are orphaned in place.
type MiroirNodeGroupApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *MiroirNodeGroupSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                           *MiroirNodeGroupStatusApplyConfiguration `json:"status,omitempty"`
}

// MiroirNodeGroup constructs a declarative configuration of the MiroirNodeGroup type for use with
// apply.
func MiroirNodeGroup(name string) *MiroirNodeGroupApplyConfiguration {
	b := &MiroirNodeGroupApplyConfiguration{}
	b.WithName(name)
	b.WithKind("MiroirNodeGroup")
	b.WithAPIVersion("miroir.home-operations.com/v1alpha1")
	return b
}

// ExtractMiroirNodeGroupFrom extracts the applied configuration owned by fieldManager from
// miroirNodeGroup for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// miroirNodeGroup must be a unmodified MiroirNodeGroup API object that was retrieved from the Kubernetes API.
// ExtractMiroirNodeGroupFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractMiroirNodeGroupFrom(miroirNodeGroup *apiv1alpha1.MiroirNodeGroup, fieldManager string, subresource string) (*MiroirNodeGroupApplyConfiguration, error) {
	b := &MiroirNodeGroupApplyConfiguration{}
	err := managedfields.ExtractInto(miroirNodeGroup, internal.Parser().Type("com.github.home-operations.miroir.api.v1alpha1.MiroirNodeGroup"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(miroirNodeGroup.Name)

	b.WithKind("MiroirNodeGroup")
	b.WithAPIVersion("miroir.home-operations.com/v1alpha1")
	return b, nil
}

// ExtractMiroirNodeGroup extracts the applied configuration owned by fieldManager from
// miroirNodeGroup. If no managedFields are found in miroirNodeGroup for fieldManager, a
// MiroirNodeGroupApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// miroirNodeGroup must be a unmodified MiroirNodeGroup API object that was retrieved from the Kubernetes API.
// ExtractMiroirNodeGroup provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractMiroirNodeGroup(miroirNodeGroup *apiv1alpha1.MiroirNodeGroup, fieldManager string) (*MiroirNodeGroupApplyConfiguration, error) {
	return ExtractMiroirNodeGroupFrom(miroirNodeGroup, fieldManager, "")
}

// ExtractMiroirNodeGroupStatus extracts the applied configuration owned by fieldManager from
// miroirNodeGroup for the status subresource.
func ExtractMiroirNodeGroupStatus(miroirNodeGroup *apiv1alpha1.MiroirNodeGroup, fieldManager string) (*MiroirNodeGroupApplyConfiguration, error) {
	return ExtractMiroirNodeGroupFrom(miroirNodeGroup, fieldManager, "status")
}

func (b MiroirNodeGroupApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithKind(value string) *MiroirNodeGroupApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithAPIVersion(value string) *MiroirNodeGroupApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithName(value string) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithGenerateName(value string) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithNamespace(value string) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithUID(value types.UID) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithResourceVersion(value string) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithGeneration(value int64) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithCreationTimestamp(value metav1.Time) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *MiroirNodeGroupApplyConfiguration) WithLabels(entries map[string]string) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *MiroirNodeGroupApplyConfiguration) WithAnnotations(entries map[string]string) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *MiroirNodeGroupApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *MiroirNodeGroupApplyConfiguration) WithFinalizers(values ...string) *MiroirNodeGroupApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *MiroirNodeGroupApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithSpec(value *MiroirNodeGroupSpecApplyConfiguration) *MiroirNodeGroupApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *MiroirNodeGroupApplyConfiguration) WithStatus(value *MiroirNodeGroupStatusApplyConfiguration) *MiroirNodeGroupApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *MiroirNodeGroupApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *MiroirNodeGroupApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *MiroirNodeGroupApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *MiroirNodeGroupApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
