/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/home-operations/miroir/api/v1alpha1"
)

// MiroirVolumeSpecApplyConfiguration represents a declarative configuration of the MiroirVolumeSpec type for use
// with apply.
//
// MiroirVolumeSpec is the desired state, written by the controller at
// CreateVolume time and reconciled by node agents. Replicas may be edited
// on a live replicated volume — add an entry (node + backend; the
// membership reconciler completes it) or remove one — within the bounds
// the validation rule pins: an unreplicated volume cannot grow a
// replication layer in place (internal DRBD metadata cannot be added
// under a live filesystem), and a replicated one keeps 2–3 replicas.
type MiroirVolumeSpecApplyConfiguration struct {
	// SizeBytes is the provisioned (virtual, thin) size of the volume.
	SizeBytes *int64 `json:"sizeBytes,omitempty"`
	// Replicas lists the placement of the volume: one entry for local
	// volumes, two or more for DRBD-replicated ones. MaxItems matches the
	// CEL size rule and bounds the apiserver's CEL cost estimate — the
	// diskless transition rule is nested over this list and exceeds the
	// rule budget on an unbounded array.
	Replicas []ReplicaApplyConfiguration `json:"replicas,omitempty"`
	// QuorumPolicy applies only when len(Replicas) > 1.
	QuorumPolicy *apiv1alpha1.QuorumPolicy `json:"quorumPolicy,omitempty"`
	// DRBD is set by the controller when len(Replicas) > 1.
	DRBD *DRBDSpecApplyConfiguration `json:"drbd,omitempty"`
	// Source, if set, provisions content from a snapshot (CoW clone).
	Source *VolumeSourceApplyConfiguration `json:"source,omitempty"`
	// Export, if set, serves the volume as a shared filesystem over NFS
	// (RWX). Set by the controller when the volume is created from a
	// MULTI_NODE access mode; immutable.
	Export *ExportSpecApplyConfiguration `json:"export,omitempty"`
}

// MiroirVolumeSpecApplyConfiguration constructs a declarative configuration of the MiroirVolumeSpec type for use with
// apply.
func MiroirVolumeSpec() *MiroirVolumeSpecApplyConfiguration {
	return &MiroirVolumeSpecApplyConfiguration{}
}

// WithSizeBytes sets the SizeBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SizeBytes field is set to the value of the last call.
func (b *MiroirVolumeSpecApplyConfiguration) WithSizeBytes(value int64) *MiroirVolumeSpecApplyConfiguration {
	b.SizeBytes = &value
	return b
}

// WithReplicas adds the given value to the Replicas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Replicas field.
func (b *MiroirVolumeSpecApplyConfiguration) WithReplicas(values ...*ReplicaApplyConfiguration) *MiroirVolumeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithReplicas")
		}
		b.Replicas = append(b.Replicas, *values[i])
	}
	return b
}

// WithQuorumPolicy sets the QuorumPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QuorumPolicy field is set to the value of the last call.
func (b *MiroirVolumeSpecApplyConfiguration) WithQuorumPolicy(value apiv1alpha1.QuorumPolicy) *MiroirVolumeSpecApplyConfiguration {
	b.QuorumPolicy = &value
	return b
}

// WithDRBD sets the DRBD field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DRBD field is set to the value of the last call.
func (b *MiroirVolumeSpecApplyConfiguration) WithDRBD(value *DRBDSpecApplyConfiguration) *MiroirVolumeSpecApplyConfiguration {
	b.DRBD = value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *MiroirVolumeSpecApplyConfiguration) WithSource(value *VolumeSourceApplyConfiguration) *MiroirVolumeSpecApplyConfiguration {
	b.Source = value
	return b
}

// WithExport sets the Export field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Export field is set to the value of the last call.
func (b *MiroirVolumeSpecApplyConfiguration) WithExport(value *ExportSpecApplyConfiguration) *MiroirVolumeSpecApplyConfiguration {
	b.Export = value
	return b
}
