/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/home-operations/miroir/api/v1alpha1"
)

// MiroirNodePoolApplyConfiguration represents a declarative configuration of the MiroirNodePool type for use
// with apply.
//
// MiroirNodePool is one named storage pool on a node: the backend
// implementation plus that backend's configuration block. Pool names are
// cluster-wide identities — a StorageClass selects a pool by name and the
// controller places each replica on a node carrying that pool.
type MiroirNodePoolApplyConfiguration struct {
	// Name is the pool name ("default" for the pre-multi-pool single
	// pool). It becomes an LVM VG name suffix, a metric label value, and a
	// StorageClass parameter, so it stays a short lowercase identifier.
	Name *string `json:"name,omitempty"`
	// Backend is the storage implementation backing this pool. An explicit
	// discriminator (not inferred from the block below): it is also
	// persisted per Replica, beyond pool config.
	Backend *apiv1alpha1.BackendType `json:"backend,omitempty"`
	// LVMThin configures the pool when backend is lvmthin.
	LVMThin *LVMThinPoolApplyConfiguration `json:"lvmthin,omitempty"`
	// ZFS configures the pool when backend is zfs.
	ZFS *ZFSPoolApplyConfiguration `json:"zfs,omitempty"`
	// Loopfile configures the pool when backend is loopfile.
	Loopfile *LoopfilePoolApplyConfiguration `json:"loopfile,omitempty"`
}

// MiroirNodePoolApplyConfiguration constructs a declarative configuration of the MiroirNodePool type for use with
// apply.
func MiroirNodePool() *MiroirNodePoolApplyConfiguration {
	return &MiroirNodePoolApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MiroirNodePoolApplyConfiguration) WithName(value string) *MiroirNodePoolApplyConfiguration {
	b.Name = &value
	return b
}

// WithBackend sets the Backend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backend field is set to the value of the last call.
func (b *MiroirNodePoolApplyConfiguration) WithBackend(value apiv1alpha1.BackendType) *MiroirNodePoolApplyConfiguration {
	b.Backend = &value
	return b
}

// WithLVMThin sets the LVMThin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LVMThin field is set to the value of the last call.
func (b *MiroirNodePoolApplyConfiguration) WithLVMThin(value *LVMThinPoolApplyConfiguration) *MiroirNodePoolApplyConfiguration {
	b.LVMThin = value
	return b
}

// WithZFS sets the ZFS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ZFS field is set to the value of the last call.
func (b *MiroirNodePoolApplyConfiguration) WithZFS(value *ZFSPoolApplyConfiguration) *MiroirNodePoolApplyConfiguration {
	b.ZFS = value
	return b
}

// WithLoopfile sets the Loopfile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Loopfile field is set to the value of the last call.
func (b *MiroirNodePoolApplyConfiguration) WithLoopfile(value *LoopfilePoolApplyConfiguration) *MiroirNodePoolApplyConfiguration {
	b.Loopfile = value
	return b
}
