/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MiroirSnapshotSpecApplyConfiguration represents a declarative configuration of the MiroirSnapshotSpec type for use
// with apply.
//
// MiroirSnapshotSpec is the desired state, created by the controller on
// CSI CreateSnapshot.
type MiroirSnapshotSpecApplyConfiguration struct {
	// VolumeName references the MiroirVolume this snapshot captures.
	// Immutable: the backend CoW snapshots were cut on the source volume's
	// replicas, so retargeting the reference would point restores and
	// per-node teardown at a volume that never held them.
	VolumeName *string `json:"volumeName,omitempty"`
}

// MiroirSnapshotSpecApplyConfiguration constructs a declarative configuration of the MiroirSnapshotSpec type for use with
// apply.
func MiroirSnapshotSpec() *MiroirSnapshotSpecApplyConfiguration {
	return &MiroirSnapshotSpecApplyConfiguration{}
}

// WithVolumeName sets the VolumeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeName field is set to the value of the last call.
func (b *MiroirSnapshotSpecApplyConfiguration) WithVolumeName(value string) *MiroirSnapshotSpecApplyConfiguration {
	b.VolumeName = &value
	return b
}
