/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/home-operations/miroir/api/v1alpha1"
)

// MiroirNodeSpecApplyConfiguration represents a declarative configuration of the MiroirNodeSpec type for use
// with apply.
//
// MiroirNodeSpec records which backend a storage node runs, mirrored from
// the node map so `kubectl get miroirnodes` reads without the ConfigMap.
type MiroirNodeSpecApplyConfiguration struct {
	// Backend is the storage implementation backing this node's pool.
	Backend *apiv1alpha1.BackendType `json:"backend,omitempty"`
}

// MiroirNodeSpecApplyConfiguration constructs a declarative configuration of the MiroirNodeSpec type for use with
// apply.
func MiroirNodeSpec() *MiroirNodeSpecApplyConfiguration {
	return &MiroirNodeSpecApplyConfiguration{}
}

// WithBackend sets the Backend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backend field is set to the value of the last call.
func (b *MiroirNodeSpecApplyConfiguration) WithBackend(value apiv1alpha1.BackendType) *MiroirNodeSpecApplyConfiguration {
	b.Backend = &value
	return b
}
