/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MiroirNodeSpecApplyConfiguration represents a declarative configuration of the MiroirNodeSpec type for use
// with apply.
//
// MiroirNodeSpec is one storage node's desired topology: its named pools
// plus node-level replication settings. Rendered by the Helm chart from
// the release's `nodes` values; read by the controller for placement and
// by the node's agent for backend selection.
type MiroirNodeSpecApplyConfiguration struct {
	// Zone is an optional failure domain (rack, host group, AZ). When set,
	// the controller spreads a volume's replicas across distinct zones;
	// empty means unconstrained.
	Zone *string `json:"zone,omitempty"`
	// Address optionally pins the node's DRBD replication endpoint to a
	// dedicated storage NIC/VLAN IP (IPv4 or IPv6); empty falls back to
	// the node's InternalIP. It applies to volumes created afterwards —
	// existing volumes keep the address persisted at creation. An explicit
	// empty string means unset (0.10 values files carry them).
	Address *string `json:"address,omitempty"`
	// AutoEvict, when explicitly false, exempts this node from auto-evict:
	// its legs are never re-placed while its heartbeat is stale (a node
	// with known long outages). Absent means eligible.
	AutoEvict *bool `json:"autoEvict,omitempty"`
	// Pools lists this node's storage pools, one entry per pool. Every
	// node in the topology carries at least one.
	Pools []MiroirNodePoolApplyConfiguration `json:"pools,omitempty"`
}

// MiroirNodeSpecApplyConfiguration constructs a declarative configuration of the MiroirNodeSpec type for use with
// apply.
func MiroirNodeSpec() *MiroirNodeSpecApplyConfiguration {
	return &MiroirNodeSpecApplyConfiguration{}
}

// WithZone sets the Zone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Zone field is set to the value of the last call.
func (b *MiroirNodeSpecApplyConfiguration) WithZone(value string) *MiroirNodeSpecApplyConfiguration {
	b.Zone = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *MiroirNodeSpecApplyConfiguration) WithAddress(value string) *MiroirNodeSpecApplyConfiguration {
	b.Address = &value
	return b
}

// WithAutoEvict sets the AutoEvict field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoEvict field is set to the value of the last call.
func (b *MiroirNodeSpecApplyConfiguration) WithAutoEvict(value bool) *MiroirNodeSpecApplyConfiguration {
	b.AutoEvict = &value
	return b
}

// WithPools adds the given value to the Pools field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Pools field.
func (b *MiroirNodeSpecApplyConfiguration) WithPools(values ...*MiroirNodePoolApplyConfiguration) *MiroirNodeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPools")
		}
		b.Pools = append(b.Pools, *values[i])
	}
	return b
}
