/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ReplicaStatusApplyConfiguration represents a declarative configuration of the ReplicaStatus type for use
// with apply.
//
// ReplicaStatus is the per-node observed state, written by that node's agent.
type ReplicaStatusApplyConfiguration struct {
	// DeviceCreated is true once the backing device exists on the node.
	DeviceCreated *bool `json:"deviceCreated,omitempty"`
	// DevicePath is the node-local path pods attach to (backing device for
	// replicas:1; /dev/drbd<minor> when replicated).
	DevicePath *string `json:"devicePath,omitempty"`
	// SizeBytes is the currently realized size on this node, used to
	// acknowledge expansion.
	SizeBytes *int64 `json:"sizeBytes,omitempty"`
	// DRBDMinor is the DRBD device minor assigned locally by the agent.
	// Zero means unassigned (fresh volume or unreplicated).
	DRBDMinor *int32 `json:"drbdMinor,omitempty"`
	// DiskState is the DRBD disk state on this node (UpToDate,
	// Inconsistent, Outdated, Diskless, …). Empty for unreplicated volumes.
	DiskState *string `json:"diskState,omitempty"`
	// Connected is true when this node's replication links to every
	// diskful peer are established. A diskless tie-breaker's link state
	// is deliberately excluded: it holds no data leg, so its downtime
	// must not read as degraded replication (it would block snapshots
	// and replica removal). Always true for unreplicated volumes.
	Connected *bool `json:"connected,omitempty"`
	// SplitBrain is true when this node's DRBD refused a reconnect after
	// detecting divergent data — operator intervention required.
	SplitBrain *bool `json:"splitBrain,omitempty"`
	// Diskless records that this node's replica is a quorum-only
	// tie-breaker. Self-reported by the agent so removal handling still
	// knows after the entry has left spec.replicas.
	Diskless *bool `json:"diskless,omitempty"`
	// DiskFailed latches a diskful leg DRBD detached after a backing I/O
	// error (on-io-error detach): the agent renders `adjust --skip-disk`
	// so the next reconcile does not re-attach the failing disk and
	// re-trigger the error. Sticky until the replica is removed and
	// re-added (a fresh backing clears it). Serving continues via the peer.
	DiskFailed *bool `json:"diskFailed,omitempty"`
	// Message carries the last reconcile error, if any.
	Message *string `json:"message,omitempty"`
}

// ReplicaStatusApplyConfiguration constructs a declarative configuration of the ReplicaStatus type for use with
// apply.
func ReplicaStatus() *ReplicaStatusApplyConfiguration {
	return &ReplicaStatusApplyConfiguration{}
}

// WithDeviceCreated sets the DeviceCreated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceCreated field is set to the value of the last call.
func (b *ReplicaStatusApplyConfiguration) WithDeviceCreated(value bool) *ReplicaStatusApplyConfiguration {
	b.DeviceCreated = &value
	return b
}

// WithDevicePath sets the DevicePath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DevicePath field is set to the value of the last call.
func (b *ReplicaStatusApplyConfiguration) WithDevicePath(value string) *ReplicaStatusApplyConfiguration {
	b.DevicePath = &value
	return b
}

// WithSizeBytes sets the SizeBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SizeBytes field is set to the value of the last call.
func (b *ReplicaStatusApplyConfiguration) WithSizeBytes(value int64) *ReplicaStatusApplyConfiguration {
	b.SizeBytes = &value
	return b
}

// WithDRBDMinor sets the DRBDMinor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DRBDMinor field is set to the value of the last call.
func (b *ReplicaStatusApplyConfiguration) WithDRBDMinor(value int32) *ReplicaStatusApplyConfiguration {
	b.DRBDMinor = &value
	return b
}

// WithDiskState sets the DiskState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskState field is set to the value of the last call.
func (b *ReplicaStatusApplyConfiguration) WithDiskState(value string) *ReplicaStatusApplyConfiguration {
	b.DiskState = &value
	return b
}

// WithConnected sets the Connected field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Connected field is set to the value of the last call.
func (b *ReplicaStatusApplyConfiguration) WithConnected(value bool) *ReplicaStatusApplyConfiguration {
	b.Connected = &value
	return b
}

// WithSplitBrain sets the SplitBrain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SplitBrain field is set to the value of the last call.
func (b *ReplicaStatusApplyConfiguration) WithSplitBrain(value bool) *ReplicaStatusApplyConfiguration {
	b.SplitBrain = &value
	return b
}

// WithDiskless sets the Diskless field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Diskless field is set to the value of the last call.
func (b *ReplicaStatusApplyConfiguration) WithDiskless(value bool) *ReplicaStatusApplyConfiguration {
	b.Diskless = &value
	return b
}

// WithDiskFailed sets the DiskFailed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskFailed field is set to the value of the last call.
func (b *ReplicaStatusApplyConfiguration) WithDiskFailed(value bool) *ReplicaStatusApplyConfiguration {
	b.DiskFailed = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ReplicaStatusApplyConfiguration) WithMessage(value string) *ReplicaStatusApplyConfiguration {
	b.Message = &value
	return b
}
