/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/home-operations/miroir/api/v1alpha1"
)

// ReplicaApplyConfiguration represents a declarative configuration of the Replica type for use
// with apply.
//
// Replica is one placement of the volume's data — a DRBD peer when the
// volume is replicated.
type ReplicaApplyConfiguration struct {
	// Node is the Kubernetes node name hosting this replica.
	Node *string `json:"node,omitempty"`
	// Backend selects how the backing device is provisioned on this node.
	// Unused for diskless tie-breaker replicas (they have no backing device).
	Backend *apiv1alpha1.BackendType `json:"backend,omitempty"`
	// NodeID is the DRBD node id, assigned by the controller at creation
	// and stable for the volume's lifetime. Only set on replicated volumes.
	NodeID *int32 `json:"nodeID,omitempty"`
	// Address is the replication endpoint (host IP), from the node map.
	// Only set on replicated volumes.
	Address *string `json:"address,omitempty"`
	// FullSync marks a replica added after volume creation: its agent
	// skips the day0 GI seed so DRBD full-syncs it from the existing
	// peers instead of treating it as a pristine twin. Set by the
	// membership reconciler when it completes the entry.
	FullSync *bool `json:"fullSync,omitempty"`
	// Diskless makes this a quorum-only tie-breaker: DRBD joins for
	// voting but stores no data. No backend device, never a mount
	// target. The agent skips backend create/resize/delete and DRBD
	// create-md; the resource renders "disk none" for this peer.
	Diskless *bool `json:"diskless,omitempty"`
}

// ReplicaApplyConfiguration constructs a declarative configuration of the Replica type for use with
// apply.
func Replica() *ReplicaApplyConfiguration {
	return &ReplicaApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *ReplicaApplyConfiguration) WithNode(value string) *ReplicaApplyConfiguration {
	b.Node = &value
	return b
}

// WithBackend sets the Backend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backend field is set to the value of the last call.
func (b *ReplicaApplyConfiguration) WithBackend(value apiv1alpha1.BackendType) *ReplicaApplyConfiguration {
	b.Backend = &value
	return b
}

// WithNodeID sets the NodeID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeID field is set to the value of the last call.
func (b *ReplicaApplyConfiguration) WithNodeID(value int32) *ReplicaApplyConfiguration {
	b.NodeID = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *ReplicaApplyConfiguration) WithAddress(value string) *ReplicaApplyConfiguration {
	b.Address = &value
	return b
}

// WithFullSync sets the FullSync field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FullSync field is set to the value of the last call.
func (b *ReplicaApplyConfiguration) WithFullSync(value bool) *ReplicaApplyConfiguration {
	b.FullSync = &value
	return b
}

// WithDiskless sets the Diskless field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Diskless field is set to the value of the last call.
func (b *ReplicaApplyConfiguration) WithDiskless(value bool) *ReplicaApplyConfiguration {
	b.Diskless = &value
	return b
}
