/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// VolumeSourceApplyConfiguration represents a declarative configuration of the VolumeSource type for use
// with apply.
//
// VolumeSource provisions the volume's content from an existing snapshot.
type VolumeSourceApplyConfiguration struct {
	// SnapshotName references a MiroirSnapshot by name.
	SnapshotName *string `json:"snapshotName,omitempty"`
	// PadForMetadata marks every diskful backing of this volume as padded
	// by the DRBD internal-metadata overhead. Set at creation when a
	// restore crosses the replication boundary (an unreplicated source
	// restored into a replicated volume, directly or transitively): the
	// source filesystem spans its full nominal size, so internal metadata
	// only fits if every leg's backing is grown past sizeBytes — the
	// clone before create-md, and full-sync joiners at creation, or the
	// device would size below the filesystem. Inherited by replicated
	// restores of padded volumes; immutable with the rest of the source.
	PadForMetadata *bool `json:"padForMetadata,omitempty"`
}

// VolumeSourceApplyConfiguration constructs a declarative configuration of the VolumeSource type for use with
// apply.
func VolumeSource() *VolumeSourceApplyConfiguration {
	return &VolumeSourceApplyConfiguration{}
}

// WithSnapshotName sets the SnapshotName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SnapshotName field is set to the value of the last call.
func (b *VolumeSourceApplyConfiguration) WithSnapshotName(value string) *VolumeSourceApplyConfiguration {
	b.SnapshotName = &value
	return b
}

// WithPadForMetadata sets the PadForMetadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PadForMetadata field is set to the value of the last call.
func (b *VolumeSourceApplyConfiguration) WithPadForMetadata(value bool) *VolumeSourceApplyConfiguration {
	b.PadForMetadata = &value
	return b
}
