/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// VolumeClientApplyConfiguration represents a declarative configuration of the VolumeClient type for use
// with apply.
//
// VolumeClient is an ephemeral diskless consumer leg: a DRBD peer with no
// backing device on a node that runs a pod but holds no replica. All its
// I/O crosses the replication network. Added by the CSI node service at
// stage time (spec.allowRemoteAccess volumes only), completed by the
// membership reconciler like a replica, removed at unstage. Unlike a
// diskless tie-breaker it is not placed for quorum — but DRBD counts every
// peer's vote, so an attached client does shift quorum math (see README).
type VolumeClientApplyConfiguration struct {
	// Node is the Kubernetes node name consuming the volume remotely.
	Node *string `json:"node,omitempty"`
	// NodeID is the DRBD node id, unique across replicas and clients,
	// assigned by the membership reconciler.
	NodeID *int32 `json:"nodeID,omitempty"`
	// Address is the replication endpoint, resolved like a replica's
	// (node-map override, else the Node's InternalIP).
	Address *string `json:"address,omitempty"`
}

// VolumeClientApplyConfiguration constructs a declarative configuration of the VolumeClient type for use with
// apply.
func VolumeClient() *VolumeClientApplyConfiguration {
	return &VolumeClientApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *VolumeClientApplyConfiguration) WithNode(value string) *VolumeClientApplyConfiguration {
	b.Node = &value
	return b
}

// WithNodeID sets the NodeID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeID field is set to the value of the last call.
func (b *VolumeClientApplyConfiguration) WithNodeID(value int32) *VolumeClientApplyConfiguration {
	b.NodeID = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *VolumeClientApplyConfiguration) WithAddress(value string) *VolumeClientApplyConfiguration {
	b.Address = &value
	return b
}
