/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// VolumeSourceApplyConfiguration represents a declarative configuration of the VolumeSource type for use
// with apply.
//
// VolumeSource provisions the volume's content from an existing snapshot.
type VolumeSourceApplyConfiguration struct {
	// SnapshotName references a MiroirSnapshot by name.
	SnapshotName *string `json:"snapshotName,omitempty"`
}

// VolumeSourceApplyConfiguration constructs a declarative configuration of the VolumeSource type for use with
// apply.
func VolumeSource() *VolumeSourceApplyConfiguration {
	return &VolumeSourceApplyConfiguration{}
}

// WithSnapshotName sets the SnapshotName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SnapshotName field is set to the value of the last call.
func (b *VolumeSourceApplyConfiguration) WithSnapshotName(value string) *VolumeSourceApplyConfiguration {
	b.SnapshotName = &value
	return b
}
