/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ZFSPoolApplyConfiguration represents a declarative configuration of the ZFSPool type for use
// with apply.
//
// ZFSPool configures a zfs pool: zvols under a parent dataset. Values are
// OpenZFS property spellings, accepted verbatim by zfs(8) — canonical case
// is required (4K, lz4), not folded.
type ZFSPoolApplyConfiguration struct {
	// Dataset is the parent dataset for zvols.
	Dataset *string `json:"dataset,omitempty"`
	// Compression is the compression property for newly created zvols;
	// "inherit" uses the parent dataset's setting. Existing zvols are not
	// mutated, and snapshot clones retain their source properties. Empty
	// means the default (lz4) — 0.10 values files carry explicit empty
	// strings, and the agent has always defaulted them.
	Compression *string `json:"compression,omitempty"`
	// VolBlockSize is the volblocksize property for newly created zvols.
	// Empty means the default (4K), for the same 0.10 compatibility reason
	// as Compression.
	VolBlockSize *string `json:"volBlockSize,omitempty"`
}

// ZFSPoolApplyConfiguration constructs a declarative configuration of the ZFSPool type for use with
// apply.
func ZFSPool() *ZFSPoolApplyConfiguration {
	return &ZFSPoolApplyConfiguration{}
}

// WithDataset sets the Dataset field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Dataset field is set to the value of the last call.
func (b *ZFSPoolApplyConfiguration) WithDataset(value string) *ZFSPoolApplyConfiguration {
	b.Dataset = &value
	return b
}

// WithCompression sets the Compression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Compression field is set to the value of the last call.
func (b *ZFSPoolApplyConfiguration) WithCompression(value string) *ZFSPoolApplyConfiguration {
	b.Compression = &value
	return b
}

// WithVolBlockSize sets the VolBlockSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolBlockSize field is set to the value of the last call.
func (b *ZFSPoolApplyConfiguration) WithVolBlockSize(value string) *ZFSPoolApplyConfiguration {
	b.VolBlockSize = &value
	return b
}
