/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package internal

import (
	fmt "fmt"
	sync "sync"

	typed "sigs.k8s.io/structured-merge-diff/v6/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.home-operations.miroir.api.v1alpha1.BackendType
  scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.DRBDSpec
  map:
    fields:
    - name: bitmapGranularityBytes
      type:
        scalar: numeric
    - name: port
      type:
        scalar: numeric
    - name: sharedSecret
      type:
        scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.ExportSpec
  map:
    fields:
    - name: fsType
      type:
        scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.ExportStatus
  map:
    fields:
    - name: address
      type:
        scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.LVMThinPool
  map:
    fields:
    - name: device
      type:
        scalar: string
    - name: poolSize
      type:
        scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.LoopfilePool
  map:
    fields:
    - name: baseDir
      type:
        scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirNode
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.MiroirNodeSpec
    - name: status
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.MiroirNodeStatus
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirNodeGroup
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.MiroirNodeGroupSpec
    - name: status
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.MiroirNodeGroupStatus
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirNodeGroupSpec
  map:
    fields:
    - name: nodeSelector
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
    - name: template
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.MiroirNodeSpec
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirNodeGroupStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: atomic
    - name: nodes
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: observedGeneration
      type:
        scalar: numeric
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirNodePool
  map:
    fields:
    - name: loopfile
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.LoopfilePool
    - name: lvmthin
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.LVMThinPool
    - name: name
      type:
        scalar: string
    - name: zfs
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.ZFSPool
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirNodePoolStatus
  map:
    fields:
    - name: allocatedBytes
      type:
        scalar: numeric
    - name: capacityBytes
      type:
        scalar: numeric
    - name: message
      type:
        scalar: string
    - name: metaUsedPercent
      type:
        scalar: numeric
    - name: name
      type:
        scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirNodeSpec
  map:
    fields:
    - name: address
      type:
        scalar: string
    - name: autoEvict
      type:
        scalar: boolean
    - name: pools
      type:
        list:
          elementType:
            namedType: com.github.home-operations.miroir.api.v1alpha1.MiroirNodePool
          elementRelationship: associative
          keys:
          - name
    - name: zone
      type:
        scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirNodeStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: atomic
    - name: drbdVersion
      type:
        scalar: string
    - name: observedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: pools
      type:
        list:
          elementType:
            namedType: com.github.home-operations.miroir.api.v1alpha1.MiroirNodePoolStatus
          elementRelationship: associative
          keys:
          - name
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirSnapshot
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.MiroirSnapshotSpec
    - name: status
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.MiroirSnapshotStatus
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirSnapshotSpec
  map:
    fields:
    - name: volumeName
      type:
        scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirSnapshotStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: atomic
    - name: ioSuspended
      type:
        scalar: boolean
    - name: perNode
      type:
        map:
          elementType:
            namedType: com.github.home-operations.miroir.api.v1alpha1.SnapshotNodeState
    - name: readyToUse
      type:
        scalar: boolean
    - name: sizeBytes
      type:
        scalar: numeric
    - name: sourceFormatted
      type:
        scalar: boolean
    - name: suspendedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirVolume
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.MiroirVolumeSpec
    - name: status
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.MiroirVolumeStatus
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirVolumeSpec
  map:
    fields:
    - name: allowRemoteAccess
      type:
        scalar: boolean
    - name: clients
      type:
        list:
          elementType:
            namedType: com.github.home-operations.miroir.api.v1alpha1.VolumeClient
          elementRelationship: atomic
    - name: drbd
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.DRBDSpec
    - name: export
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.ExportSpec
    - name: quorumPolicy
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.QuorumPolicy
    - name: replicas
      type:
        list:
          elementType:
            namedType: com.github.home-operations.miroir.api.v1alpha1.Replica
          elementRelationship: atomic
    - name: sizeBytes
      type:
        scalar: numeric
    - name: source
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.VolumeSource
- name: com.github.home-operations.miroir.api.v1alpha1.MiroirVolumeStatus
  map:
    fields:
    - name: activated
      type:
        scalar: boolean
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: atomic
    - name: export
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.ExportStatus
    - name: formatted
      type:
        scalar: boolean
    - name: perNode
      type:
        map:
          elementType:
            namedType: com.github.home-operations.miroir.api.v1alpha1.ReplicaStatus
    - name: phase
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.VolumePhase
- name: com.github.home-operations.miroir.api.v1alpha1.QuorumPolicy
  scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.Replica
  map:
    fields:
    - name: address
      type:
        scalar: string
    - name: backend
      type:
        namedType: com.github.home-operations.miroir.api.v1alpha1.BackendType
    - name: diskless
      type:
        scalar: boolean
    - name: fullSync
      type:
        scalar: boolean
    - name: node
      type:
        scalar: string
    - name: nodeID
      type:
        scalar: numeric
    - name: pool
      type:
        scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.ReplicaStatus
  map:
    fields:
    - name: connected
      type:
        scalar: boolean
    - name: deviceCreated
      type:
        scalar: boolean
    - name: devicePath
      type:
        scalar: string
    - name: discardGranularityBytes
      type:
        scalar: numeric
    - name: diskFailed
      type:
        scalar: boolean
    - name: diskState
      type:
        scalar: string
    - name: diskless
      type:
        scalar: boolean
    - name: drbdMinor
      type:
        scalar: numeric
    - name: lastVerifyOutOfSyncBytes
      type:
        scalar: numeric
    - name: lastVerifyTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: message
      type:
        scalar: string
    - name: pool
      type:
        scalar: string
    - name: primarySince
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: sizeBytes
      type:
        scalar: numeric
    - name: splitBrain
      type:
        scalar: boolean
- name: com.github.home-operations.miroir.api.v1alpha1.SnapshotNodeState
  scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.VolumeClient
  map:
    fields:
    - name: addedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: address
      type:
        scalar: string
    - name: node
      type:
        scalar: string
    - name: nodeID
      type:
        scalar: numeric
- name: com.github.home-operations.miroir.api.v1alpha1.VolumePhase
  scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.VolumeSource
  map:
    fields:
    - name: snapshotName
      type:
        scalar: string
- name: com.github.home-operations.miroir.api.v1alpha1.ZFSPool
  map:
    fields:
    - name: compression
      type:
        scalar: string
      default: lz4
    - name: dataset
      type:
        scalar: string
    - name: volBlockSize
      type:
        scalar: string
      default: 4K
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: message
      type:
        scalar: string
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
    - name: status
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ConditionStatus
    - name: type
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ConditionStatus
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
  map:
    fields:
    - name: matchExpressions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement
          elementRelationship: atomic
    - name: matchLabels
      type:
        map:
          elementType:
            scalar: string
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorOperator
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement
  map:
    fields:
    - name: key
      type:
        scalar: string
    - name: operator
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorOperator
    - name: values
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: io.k8s.apimachinery.pkg.types.UID
  scalar: string
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
