/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package drbd drives the in-kernel DRBD9 replication layer: it renders
// resource config files and wraps drbdadm/drbdmeta/drbdsetup. The CRD is
// the source of truth — rendering is deterministic (sorted peers, no map
// iteration) so reconcilers can compare bytes and skip no-op adjusts.
package drbd

import (
	"cmp"
	"fmt"
	"net"
	"slices"
	"strings"

	miroirv1alpha1 "github.com/home-operations/miroir/api/v1alpha1"
)

// peerDiskPlaceholder stands in for remote backing devices in `on` blocks:
// DRBD never reads a peer's disk path, but the parser requires a non-empty
// token, and the local render must not depend on remote pool layout.
const peerDiskPlaceholder = "/dev/drbd/this/is/not/used"

// Resource is everything needed to render one DRBD resource config on one
// node.
type Resource struct {
	// Name is the DRBD resource name (the volume name).
	Name string
	// Minor is the DRBD device minor (/dev/drbd<minor>).
	Minor int32
	// Port is the TCP port for all of this resource's connections.
	Port int32
	// Quorum selects the 2-node consistency mode.
	Quorum miroirv1alpha1.QuorumPolicy
	// LocalNode is the node this config is rendered on; its peer entry
	// gets the real backing path, all others the placeholder.
	LocalNode string
	// LocalDisk is the local backing device path. Empty/unused when
	// LocalDiskless is true.
	LocalDisk string
	// LocalDiskless is true when the local node holds a diskless leg — a
	// tie-breaker replica or a client leg (spec.clients): Apply skips
	// create-md and the local peer renders "disk none".
	LocalDiskless bool
	// Secret authenticates peers (cram-hmac challenge-response). Empty
	// renders no auth — volumes created before secrets existed.
	Secret string
	// SkipDiskAttach renders `drbdadm adjust --skip-disk`: reconcile the
	// net/connection state but leave the disk detached. Set when a leg is
	// latched failed (DiskFailed) so adjust does not re-attach a disk DRBD
	// detached on an I/O error — the flap the latch exists to stop.
	SkipDiskAttach bool
	// DiscardGranularityBytes renders rs-discard-granularity in the local
	// leg's disk{} options (0 renders nothing): a resync sends zero-runs
	// as discards of this size, keeping a FullSync-joining thin leg thin.
	// Probed from the backing device; never set for loopfile (loop devices
	// mishandle it). Overrides the cluster-wide common{} knob.
	DiscardGranularityBytes int64
	// ClientDiscardGranularityBytes renders discard-granularity in the
	// local client leg's disk{} options: the diskless device advertises
	// this to the filesystem instead of DRBD's 512-byte diskless default,
	// so consumer-side mkfs/fstrim discards align with the diskful legs'
	// real backings. 0 renders nothing (keeps the kernel heuristic).
	// Needs kmod ≥ 9.3.1 / utils ≥ 9.34 — the agent's startup floor.
	ClientDiscardGranularityBytes int64
	// BitmapGranularityBytes is passed to create-md as
	// --bitmap-block-size (0 passes nothing, DRBD defaults to 4k). Not
	// rendered into the .res: it is an on-disk metadata property fixed
	// when this leg's metadata is created.
	BitmapGranularityBytes int64
	// Peers are all members of the resource, including the local node.
	// A Peer with Diskless=true renders "disk none" and omits meta-disk.
	Peers []Peer
}

// Peer is one member of the resource (diskful or diskless).
type Peer struct {
	Node    string
	NodeID  int32
	Address string
	// Diskless marks a peer with no backing device — a quorum-only
	// tie-breaker or a client leg: renders "disk none", no meta-disk,
	// no backend.
	Diskless bool
	// Client marks a diskless consumer leg (spec.clients): rendered with
	// "tiebreaker no" so DRBD never counts its vote, unlike a placed
	// tie-breaker replica whose vote is its purpose.
	Client bool
}

// Render produces the .res file content for the local node.
func Render(r Resource) string {
	peers := append([]Peer(nil), r.Peers...)
	slices.SortFunc(peers, func(a, b Peer) int { return cmp.Compare(a.NodeID, b.NodeID) })

	var b strings.Builder
	fmt.Fprintf(&b, "# generated by miroir — do not edit (source: MiroirVolume %s)\n", r.Name)
	fmt.Fprintf(&b, "resource %q {\n", r.Name)

	b.WriteString("    options {\n")
	b.WriteString("        auto-promote yes;\n")
	switch r.Quorum {
	case miroirv1alpha1.QuorumFreeze:
		// Any disconnect halts writes on both sides; never diverges.
		// No on-suspended-primary-outdated: it only acts under
		// on-no-quorum suspend-io, and keying off the suspended state
		// would entangle it with the snapshot barrier's suspend-io.
		b.WriteString("        quorum majority;\n")
		b.WriteString("        on-no-quorum io-error;\n")
	default:
		// Last-man-standing: the survivor keeps writing; split-brain is
		// detected on reconnect and surfaced for manual resolution.
		b.WriteString("        quorum off;\n")
	}
	b.WriteString("    }\n")

	b.WriteString("    net {\n")
	b.WriteString("        protocol C;\n")
	if r.Secret != "" {
		// Without auth, anything that can reach the replication port can
		// join the resource.
		b.WriteString("        cram-hmac-alg sha1;\n")
		fmt.Fprintf(&b, "        shared-secret %q;\n", r.Secret)
	}
	// Never auto-resolve diverged data: an operator picks the loser.
	// discard-zero-changes and consensus let DRBD pick
	// one — a zero-changes verdict trusts generation identifiers that
	// day0-seeded clones share without sharing history.
	b.WriteString("        after-sb-0pri disconnect;\n")
	b.WriteString("        after-sb-1pri disconnect;\n")
	b.WriteString("        after-sb-2pri disconnect;\n")
	b.WriteString("    }\n")

	for _, p := range peers {
		fmt.Fprintf(&b, "    on %q {\n", p.Node)
		fmt.Fprintf(&b, "        node-id %d;\n", p.NodeID)
		// Family-aware: an IPv6 InternalIP rendered as ipv4 is a parse
		// error that poisons drbdadm for every resource on the node.
		if ip := net.ParseIP(p.Address); ip != nil && ip.To4() == nil {
			fmt.Fprintf(&b, "        address ipv6 [%s]:%d;\n", p.Address, r.Port)
		} else {
			fmt.Fprintf(&b, "        address ipv4 %s:%d;\n", p.Address, r.Port)
		}
		b.WriteString("        volume 0 {\n")
		fmt.Fprintf(&b, "            device minor %d;\n", r.Minor)
		if p.Diskless {
			// Diskless leg: no backing device, no on-disk metadata (the
			// absent meta-disk directive means "none" for diskless peers).
			b.WriteString("            disk none;\n")
			if p.Client {
				// A client leg consumes data but is not placed for
				// quorum; without this DRBD counts its vote, raising the
				// majority threshold while a pod is attached and leaving
				// a stranded vote behind when its node dies. Tie-breaker
				// replicas keep the default yes. Needs drbd-utils ≥ 9.34
				// and kmod ≥ 9.3.1 — the agent's startup floor.
				b.WriteString("            tiebreaker no;\n")
			}
			// A second disk statement is legal: the string form (none)
			// and the options form fill different config fields — the
			// same shape the diskful branch uses for rs-discard-granularity.
			if p.Node == r.LocalNode && r.ClientDiscardGranularityBytes > 0 {
				b.WriteString("            disk {\n")
				fmt.Fprintf(&b, "                discard-granularity %d;\n", r.ClientDiscardGranularityBytes)
				b.WriteString("            }\n")
			}
		} else {
			disk := peerDiskPlaceholder
			if p.Node == r.LocalNode {
				disk = r.LocalDisk
			}
			fmt.Fprintf(&b, "            disk %q;\n", disk)
			b.WriteString("            meta-disk internal;\n")
			if p.Node == r.LocalNode && r.DiscardGranularityBytes > 0 {
				b.WriteString("            disk {\n")
				fmt.Fprintf(&b, "                rs-discard-granularity %d;\n", r.DiscardGranularityBytes)
				b.WriteString("            }\n")
			}
		}
		b.WriteString("        }\n")
		b.WriteString("    }\n")
	}

	b.WriteString("    connection-mesh {\n")
	names := make([]string, 0, len(peers))
	for _, p := range peers {
		names = append(names, fmt.Sprintf("%q", p.Node))
	}
	fmt.Fprintf(&b, "        hosts %s;\n", strings.Join(names, " "))
	b.WriteString("    }\n")

	b.WriteString("}\n")
	return b.String()
}

// DevicePath returns the DRBD device node for a minor.
func DevicePath(minor int32) string {
	return fmt.Sprintf("/dev/drbd%d", minor)
}
