/*
Copyright 2026.

Licensed under the GNU Affero General Public License, Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package drbd drives the in-kernel DRBD9 replication layer: it renders
// resource config files and wraps drbdadm/drbdmeta/drbdsetup. The CRD is
// the source of truth — rendering is deterministic (sorted peers, no map
// iteration) so reconcilers can compare bytes and skip no-op adjusts.
package drbd

import (
	"cmp"
	"fmt"
	"net"
	"slices"
	"strings"

	miroirv1alpha1 "github.com/home-operations/miroir/api/v1alpha1"
)

// peerDiskPlaceholder stands in for remote backing devices in `on` blocks:
// DRBD never reads a peer's disk path, but the parser requires a non-empty
// token, and the local render must not depend on remote pool layout.
const peerDiskPlaceholder = "/dev/drbd/this/is/not/used"

// Resource is everything needed to render one DRBD resource config on one
// node.
type Resource struct {
	// Name is the DRBD resource name (the volume name).
	Name string
	// Minor is the DRBD device minor (/dev/drbd<minor>).
	Minor int32
	// Port is the TCP port for all of this resource's connections.
	Port int32
	// Quorum selects the 2-node consistency mode (DESIGN §3.2).
	Quorum miroirv1alpha1.QuorumPolicy
	// LocalNode is the node this config is rendered on; its peer entry
	// gets the real backing path, all others the placeholder.
	LocalNode string
	// LocalDisk is the local backing device path. Empty/unused when
	// LocalDiskless is true.
	LocalDisk string
	// LocalDiskless is true when the local node is a diskless tie-breaker:
	// Apply skips create-md/seedGI and the local peer renders "disk none".
	LocalDiskless bool
	// Secret authenticates peers (cram-hmac challenge-response). Empty
	// renders no auth — volumes created before secrets existed.
	Secret string
	// SkipDiskAttach renders `drbdadm adjust --skip-disk`: reconcile the
	// net/connection state but leave the disk detached. Set when a leg is
	// latched failed (DiskFailed) so adjust does not re-attach a disk DRBD
	// detached on an I/O error — the flap the latch exists to stop.
	SkipDiskAttach bool
	// SkipSeed leaves fresh metadata at create-md's just-created state
	// instead of day0 GI seeding: a replica joining an existing volume
	// must full-sync from its peers, not pose as a pristine twin.
	SkipSeed bool
	// Peers are all members of the resource, including the local node.
	// A Peer with Diskless=true renders "disk none" and omits meta-disk.
	Peers []Peer
}

// Peer is one member of the resource (diskful or diskless).
type Peer struct {
	Node    string
	NodeID  int32
	Address string
	// Diskless marks a quorum-only tie-breaker peer: renders "disk none",
	// no meta-disk, no backend.
	Diskless bool
}

// Render produces the .res file content for the local node.
func Render(r Resource) string {
	peers := append([]Peer(nil), r.Peers...)
	slices.SortFunc(peers, func(a, b Peer) int { return cmp.Compare(a.NodeID, b.NodeID) })

	var b strings.Builder
	fmt.Fprintf(&b, "# generated by miroir — do not edit (source: MiroirVolume %s)\n", r.Name)
	fmt.Fprintf(&b, "resource %q {\n", r.Name)

	b.WriteString("    options {\n")
	b.WriteString("        auto-promote yes;\n")
	switch r.Quorum {
	case miroirv1alpha1.QuorumFreeze:
		// Any disconnect halts writes on both sides; never diverges.
		// No on-suspended-primary-outdated: it only acts under
		// on-no-quorum suspend-io, and keying off the suspended state
		// would entangle it with the snapshot barrier's suspend-io.
		b.WriteString("        quorum majority;\n")
		b.WriteString("        on-no-quorum io-error;\n")
	default:
		// Last-man-standing: the survivor keeps writing; split-brain is
		// detected on reconnect and surfaced for manual resolution.
		b.WriteString("        quorum off;\n")
	}
	b.WriteString("    }\n")

	b.WriteString("    net {\n")
	b.WriteString("        protocol C;\n")
	if r.Secret != "" {
		// Without auth, anything that can reach the replication port can
		// join the resource.
		b.WriteString("        cram-hmac-alg sha1;\n")
		fmt.Fprintf(&b, "        shared-secret %q;\n", r.Secret)
	}
	// Never auto-resolve diverged data: an operator picks the loser
	// (DESIGN §3.2). discard-zero-changes and consensus let DRBD pick
	// one — a zero-changes verdict trusts generation identifiers that
	// day0-seeded clones share without sharing history.
	b.WriteString("        after-sb-0pri disconnect;\n")
	b.WriteString("        after-sb-1pri disconnect;\n")
	b.WriteString("        after-sb-2pri disconnect;\n")
	b.WriteString("    }\n")

	for _, p := range peers {
		fmt.Fprintf(&b, "    on %q {\n", p.Node)
		fmt.Fprintf(&b, "        node-id %d;\n", p.NodeID)
		// Family-aware: an IPv6 InternalIP rendered as ipv4 is a parse
		// error that poisons drbdadm for every resource on the node.
		if ip := net.ParseIP(p.Address); ip != nil && ip.To4() == nil {
			fmt.Fprintf(&b, "        address ipv6 [%s]:%d;\n", p.Address, r.Port)
		} else {
			fmt.Fprintf(&b, "        address ipv4 %s:%d;\n", p.Address, r.Port)
		}
		b.WriteString("        volume 0 {\n")
		fmt.Fprintf(&b, "            device minor %d;\n", r.Minor)
		if p.Diskless {
			// Diskless tie-breaker: joins for quorum voting, stores no
			// data. No backing device, no on-disk metadata.
			b.WriteString("            disk none;\n")
			// No meta-disk directive — DRBD treats the absence as "no
			// metadata device" for diskless peers.
		} else {
			disk := peerDiskPlaceholder
			if p.Node == r.LocalNode {
				disk = r.LocalDisk
			}
			fmt.Fprintf(&b, "            disk %q;\n", disk)
			b.WriteString("            meta-disk internal;\n")
		}
		b.WriteString("        }\n")
		b.WriteString("    }\n")
	}

	b.WriteString("    connection-mesh {\n")
	names := make([]string, 0, len(peers))
	for _, p := range peers {
		names = append(names, fmt.Sprintf("%q", p.Node))
	}
	fmt.Fprintf(&b, "        hosts %s;\n", strings.Join(names, " "))
	b.WriteString("    }\n")

	b.WriteString("}\n")
	return b.String()
}

// DevicePath returns the DRBD device node for a minor.
func DevicePath(minor int32) string {
	return fmt.Sprintf("/dev/drbd%d", minor)
}
